use ENCHERES;
go

ALTER TABLE RETRAITS drop CONSTRAINT retrait_article_fk;
ALTER TABLE encheres drop CONSTRAINT encheres_no_article_fk;
ALTER TABLE encheres drop CONSTRAINT encheres_utilisateur_fk;
ALTER TABLE ARTICLES_VENDUS drop CONSTRAINT ventes_utilisateur_fk;
ALTER TABLE articles_vendus drop CONSTRAINT articles_vendus_categories_fk;

ALTER TABLE RETRAITS DROP CONSTRAINT retrait_pk; 
ALTER TABLE encheres DROP CONSTRAINT enchere_pk; 
ALTER TABLE ARTICLES_VENDUS DROP CONSTRAINT ARTICLES_VENDUs_pk; 
ALTER TABLE UTILISATEURS DROP CONSTRAINT utilisateur_pk; 
ALTER TABLE CATEGORIES DROP CONSTRAINT CATEGORIE_pk; 

DROP TABLE CATEGORIES; 
DROP TABLE ENCHERES; 
DROP TABLE ARTICLES_VENDUS; 
DROP TABLE RETRAITS; 
DROP TABLE UTILISATEURS;  